#
# Copyright (C) 2025 Wind River Systems, Inc.
#

# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

# Mask recipes-bsp directory while building a non-amd-versal project.
# Note that BSP_XILINX_DERIVED is defined to be amd-versal in conf/machine/amd-versal.inc
BBMASK += "${@bb.utils.contains_any('MACHINE', '${BSP_XILINX_DERIVED}', '', '${LAYERDIR}/recipes-bsp/', d)}"
BBMASK += "${@bb.utils.contains_any('MACHINE', '${BSP_XILINX_DERIVED}', '', '${LAYERDIR}/recipes-firmwares/', d)}"

BBFILE_COLLECTIONS += "wr-amd-versal"
BBFILE_PATTERN_wr-amd-versal := "^${LAYERDIR}/"
BBFILE_PRIORITY_wr-amd-versal = "7"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_wr-amd-versal = "1"

LAYERDEPENDS_wr-amd-versal = "core wrlinux xilinx xilinx-standalone meta-arm xilinx-standalone-sdt xilinx-microblaze amd-adaptive-socs-bsp"
LAYERSERIES_COMPAT_wr-amd-versal = "wrl walnascar"
